require 'rghost' 
require 'goods/item'
require 'financier/note'
require 'taxe/value'
require 'taxe/type'
require 'taxe/group'
require 'address/country'
require 'address/state'
require 'address/city'
require 'address/neighborhood'
require 'address/street'
require 'participant/person'
require 'participant/type'
require 'participant/issuer'
require 'participant/sender'
require 'participant/delivery'
require 'participant/contact'
require 'participant/contact/address'
require 'participant/contact/email'
require 'participant/contact/type'
class Report::Transaction
  
end
