development:
  adapter: mysql2
  database: crh_development
  user: root
  password: cafe
  port: 3306
  host: localhost
  encoding: utf8

test:
  adapter: mysql2
  database: crh_test
  user: root
  password: cafe
  port: 3306
  host: localhost
  encoding: utf8

production:
  adapter: jdbcpostgresql
  database: crh_production
  username: postgres
  password: cafe
  port: 5433
  hostname: localhost
  encoding: utf8

