development:
  adapter: mysql2
  database: crh_development
  user: root
  password: cafe
  port: 3306
  host: localhost
  encoding: utf8

test:
  adapter: sqlite3
  database: db/crh_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: jdbcpostgresql
  database: crh_production
  username: postgres
  password: cafe
  port: 5433
  hostname: localhost
  encoding: utf8

