development:
  adapter: jdbcmysql
  database: crh_development
  username: root
  password: cafe
  port: 3306
  hostname: localhost
  encoding: utf8

test:
  adapter: jdbcmysql
  database: crh_test
  username: root
  password: cafe
  port: 3306
  hostname: localhost
  encoding: utf8

production:
  adapter: jdbcpostgresql
  database: crh_production
  username: postgres
  password: cafe
  port: 5433
  hostname: localhost
  encoding: utf8

