development:
  adapter: mysql
  database: crh_development
  user: root
  password: cafe
  port: 3306
  host: localhost

test:
  adapter: mysql
  database: crh_test
  user: root
  password: cafe
  port: 3306
  host: localhost

production:
  adapter: mysql
  database: crh_production
  user: root
  password: cafe
  port: 3306
  host: localhost
